### PR TITLE
Remove object-assign-deep, refactor setting popper options

### PR DESCRIPTION
**Pull request by genadis**
Following https://github.com/shipshapecode/shepherd/pull/488

using 1K object-assign-deep seems overkill.

especially since their readme starts with: "Caution! Danger of Death!"
It introduces unnecessary risk fo user error.

### CODE REVIEW

**Comment by genadis** [comment]
I need to make a fix to the pull request. please wait with merge.
sorry

**Comment by rwwagner90** [comment]
@genadis removing would be great! Can you add some tests to ensure the deeply nested objects are merged?

**Comment by rwwagner90** [comment]
@genadis I can add the tests real quick, never mind, but in the future please add tests for all new PRs 😃

**Comment by rwwagner90** [comment]
@genadis I made some changes and added tests. Any issues with the changes? If not, I will merge.

**Comment by rwwagner90** [comment]
Went ahead and merged with my changes. If you have any issues. Please let me know!

**Comment by genadis** [comment]
@rwwagner90 I believe your changes have a number of issues, I've added comments inline

**Comment by genadis** [comment]
this: https://github.com/shipshapecode/shepherd/issues/486 was the original issue

**Comment by rwwagner90** [comment]
@genadis what are the issues? I do not see any comments and the issue you referenced where the shepherd class is not added is no longer an issue.

**Comment by rwwagner90** [comment]
@genadis I see the issue now, but I don't see your inline comments. Will work toward a fix. We probably should have kept deep assign.

**Comment by rwwagner90** [comment]
@genadis I just pushed the fix to master. Please let me know if you are still seeing issues or have suggestions.

**Comment by genadis** [comment]
> @genadis I see the issue now, but I don't see your inline comments. Will work toward a fix. We probably should have kept deep assign.

yes, sorry, didn't submit it. now submitted

**Comment by genadis** [comment]
> @genadis I just pushed the fix to master. Please let me know if you are still seeing issues or have suggestions.

will review, thanks

**Pull request merged**
