### PR TITLE
Removed unnecessary parenthetical commas

### PR DESCRIPTION
**Pull request by sector-f**
I removed some commas that were syntactically placed as parenthetical commas despite the contained information not actually being parenthetical.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@sector-f I'm not sure I understand why we would want to remove these.

**Comment by sector-f** [comment]
@rwwagner90 Parenthetical commas (e.g. the commas in question here) indicate that the information contained between them is not actually necessary for the meaning of the sentence. They're similar to parentheses--hence their name.

If the commas _should_ actually be there, then that means that the sentence really means "All PRs are required to have accompanying tests" (as opposed to just the PRs that change code functionality).

Removing the commas changes the sentence to mean that only PRs that change code functionality require accompanying tests. I have to assume that this is the correct interpretation of the sentence, since it really doesn't make sense for e.g. a PR that just fixes typos (like this one!) to have accompanying tests.

**Comment by sector-f** [comment]
Also, it's October and I want my Hacktoberfest shirt.

**Comment by rwwagner90** [comment]
@sector-f fair enough. We have some issues that need some help, if you would like to participate in more Hacktoberfest stuff.

**Pull request merged**
