### PR TITLE
Update theming documentation.

### PR DESCRIPTION
**Pull request by BrianSipple**
- Add screenshots to showcase each theme.
- Minor tweaks to make the theming documentation a bit more clear & concise.

### CODE REVIEW

**Comment by BrianSipple** [comment]
@rwwagner90 I want get shots for those, too. #241 got in the way, though 😂.

**Comment by rwwagner90** [comment]
Sure we can iterate. Do you want to go ahead and get this in or do you want to wait until we have shots for all the themes?

**Comment by BrianSipple** [comment]
I'm going try and get to the bottom of #241 first. I'm okay with waiting a bit here.

**Comment by rwwagner90** [comment]
I'm going to go ahead and merge this in, and we can investigate the old themes later.

**Pull request merged**
