### PR TITLE
Recreate elements each time on show

### LINKED ISSUE #580: Popover position at (0, 0) when target is rerendered
Seems like a duplicate of #112 though it is said there it should have been fixed.  
Stackblitz with example: https://stackblitz.com/edit/shepherd-rerender-target?file=index.html

### Steps to reproduce
1. Start tour.
2. Destroy and rerender the target of one of the tour steps.
3. Go to that step

### Expected result
The newly created element is highlighted and popover is targeting it.

### Actual result
Popover is positioned at (0, 0).

### PR DESCRIPTION
**Pull request by rwwagner90**
Fixes #580

### CODE REVIEW

**Comment by serhiichuk** [comment]
@rwwagner90 
I have updated the package to 5.0.1 version, bug #580 still reproducing.
It seems that you did not add the "Recreate elements each time on show" commit on NPM release. 

image
image

Can you check that?

**Comment by rwwagner90** [comment]
@serhiichuk this has not been released yet. I will get a beta out today.

**Comment by serhiichuk** [comment]
@rwwagner90 could you tell me please, when this has been released on npm?

**Comment by rwwagner90** [comment]
@serhiichuk the beta has been published https://www.npmjs.com/package/shepherd.js/v/6.0.0-beta.1

Note: v6 is a major change from v5, and there are breaking changes and it is not super polished yet, but we will have a stable v6 out soon.

**Pull request merged**
