### PR TITLE
Fix options type for `options.floatingUIOptions`

### PR DESCRIPTION
**Pull request by patrikholcak**
## About

Shepherd is already using `ComputePositionConfig` internally in a few places, but the options object itself is typed as `object`, which isn’t really helpful. Not sure if this is done because of some problem with docs — feel free to close this PR in that case!

### Proposed changes

*   add correct type to `Step.floatingUIOptions`

### CODE REVIEW

**Review by RobbieTheWagner — APPROVED** [review]

**Comment by RobbieTheWagner** [comment]
@patrikholcak hitting this error:

```
17:38:26 [ERROR] [starlight-typedoc-plugin] node_modules/shepherd.js/src/utils/floating-ui.ts:63:17 - error TS2742: The inferred type of 'mergeTooltipConfig' cannot be named without a reference to '.pnpm/@floating-ui+core@1.6.5/node_modules/@floating-ui/core'. This is likely not portable. A type annotation is necessary.
```

**Comment by patrikholcak** [comment]
Yeah, that explains why it hasn’t been added in the first place :smile: I don’t like doing it, but would you be ok with me copying some of the declarations from floating ui (bad, I know) or should I look into the docs plugin? Maybe there’s an option to ignore a type or make it "external"? :shrug:

I probably won’t have time over the weekend though

**Comment by patrikholcak** [comment]
@RobbieTheWagner it should be fixed now (works on my machine!) let me know if it does and I’ll either cherry-pick this into #3012 or wait for this to get merged and then just rebase/merge these changes into #3012

**Review by leroy182 — COMMENTED** [review]
@leroy182

**Pull request merged**
