### PR TITLE
Attempting to fix uncaught exception caused by non-existing element f…

### PR DESCRIPTION
**Pull request by IvanKarpan**
…or shepherd attachment

Hi,

There is a case when document.querySelector can throw an exception which was not handled by the library and therefore caused me some troubles (beforeShowPromise didn't fire and my perfectionism  suffered like a lot).

As per documentation on document.querySelector: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

Please kindly accept this pull request to right all wrongs.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@IvanKarpan can you please elaborate on this? How can `document.querySelector` throw an exception?

**Comment by IvanKarpan** [comment]
It happens if the selector used is malformed. I ran into this scenario because I was working on a tour guide builder of sorts where users can populate an array of steps by providing a selector and a string for each item. And the problem surfaced when they input an invalid selector which caused an exception I could not handle. Hence the pull request. :)

**Comment by rwwagner90** [comment]
@IvanKarpan but `document.querySelector('fdsafdsa')` works fine and returns `null` it does not throw an error. Can you be more specific about how there was an error thrown here please?

**Comment by IvanKarpan** [comment]
@rwwagner90 try doing `document.querySelector('')`, I mean in a scenario where it's an input from the user you can expect anything. Even if it's the developer tinkering with the library it should not shoot out exceptions for an empty string selector. The pull request I suggested catches this situation, the variable does not get populated and the library processes this as if it hasn't found the element on the page.

**Comment by rwwagner90** [comment]
Thank you for clarifying. I just thought `document.querySelector` handled its own errors. Now that I know the case in which errors are thrown, I am in support of this.

**Comment by rwwagner90** [comment]
@IvanKarpan I just merged the conversion to popper, could you please rebase?

**Comment by rwwagner90** [comment]
I fixed the conflicts in another branch and merged. Thanks so much for the PR!

**Comment by IvanKarpan** [comment]
Sorry, missed your request, thx a lot for handling the conflicts and accepting the PR!

**Pull request closed without merging**
