### PR TITLE
Optional padding on modalOverlayOpening

### PR DESCRIPTION
**Pull request by skmbr**
Relating to: https://github.com/shipshapecode/shepherd/issues/379

### CODE REVIEW

**Comment by chuckcarpenter** [comment]
@skmbr this LGTM! Thanks for taking the time. I'll merge and you can use from MASTER until the release is set.

**Comment by skmbr** [comment]
@chuckcarpenter Brilliant, thank you! :) When do think you'll be doing a release?

**Comment by rwwagner90** [comment]
@skmbr I will be home tomorrow, and I can work on the next release

**Comment by rwwagner90** [comment]
@skmbr I will be home tomorrow, and I can work on the next release

**Comment by rwwagner90** [comment]
@skmbr it appears the build is failing after merging this PR, also it would be nice to have tests and docs for this feature. Would you mind taking a look?

**Comment by skmbr** [comment]
@rwwagner90 Sorry, not had a chance to come back to this over the last few weeks.  Will try and take a look next week, but not sure where to start.  Can I see the errors from the build somewhere?  :(

**Comment by rwwagner90** [comment]
@skmbr I already fixed it, documented, and added tests 😄 https://github.com/shipshapecode/shepherd/pull/390

**Comment by skmbr** [comment]
Oh, cool! Thanks! I shall read and learn ;)

**Pull request merged**
